# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-18 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.CharField(default='Normal', max_length=100),
        ),
    ]
