# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-01 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdash', '0002_user_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
