# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-01 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdash', '0003_auto_20180601_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.CharField(default='Normal', max_length=100),
        ),
    ]
